target-version = "py312"

[lint]
select = ["A", "C90", "E", "F", "I", "N", "PL", "S", "UP", "W", "PT", "RUF", "SIM"]
ignore = ["S101", "S108"]

[lint.isort]
force-single-line = true

[lint.pylint]
max-args = 7
